using Pkg
Pkg.add("Statistics")
Pkg.add("Random")
Pkg.add("LinearAlgebra")
Pkg.add("Interpolations")
Pkg.add("DelimitedFiles")
Pkg.add("Distributed")
Pkg.add("SlimOptim")
Pkg.add("NLopt")
Pkg.add("HDF5")
Pkg.add("SegyIO")
Pkg.add("Plots")
Pkg.add("SetIntersectionProjection")
Pkg.add("ImageFiltering")
Pkg.add("DrWatson")